from application import application
from models import db, CreditCard

SEED_CARDS = [
    {
        "name": "Absa Flexi Core Credit Card",
        "banks": "ABSA",
        "card_type": "Credit",
        "interest_rate": "From prime + 6%",
        "interest_free_days": 57,
        "monthly_fee": 27.0,
        "annual_fee": 0.0,
        "min_income": "R4,000+ / month",
        "limit_range": "R1,500 to R90,000",
        "reward_type": "Everyday Value",
        "rewards_summary": "Simple entry-level card with app management, tap-to-pay, and everyday budgeting support.",
        "travel_features": "Digital wallet support and online spend control.",
        "lifestyle_features": "Instant notifications, flexible repayments, card freeze in app.",
        "insurance": "Optional credit protection",
        "discounts": "Selected Absa partner promotions",
        "requirements": "South African ID, income proof, healthy affordability assessment.",
        "benefits": "Good starting point for building credit with manageable fees.",
        "risks": "Interest rises quickly if balances are revolved without a repayment plan.",
        "pros": "Accessible entry point\nUseful app controls\nStrong everyday acceptance",
        "cons": "Limited premium perks\nRewards are lighter than higher tiers",
        "categories": "Everyday,Rewards",
        "tier": "Standard",
        "is_featured": True,
        "brochure_link": "https://www.absa.co.za/personal/credit-cards/",
    },
    {
        "name": "Absa Gold Credit Card",
        "banks": "ABSA",
        "card_type": "Credit",
        "interest_rate": "From prime + 4.75%",
        "interest_free_days": 57,
        "monthly_fee": 51.0,
        "annual_fee": 0.0,
        "min_income": "R8,000+ / month",
        "limit_range": "R15,000 to R120,000",
        "reward_type": "Absa Rewards",
        "rewards_summary": "Balanced rewards card with higher limits, dining offers, and better travel flexibility.",
        "travel_features": "Travel booking offers and global card acceptance.",
        "lifestyle_features": "Dining, shopping, and digital wallet compatibility.",
        "insurance": "Basic travel inconvenience and card protection benefits",
        "discounts": "Rotating Absa Rewards partner offers",
        "requirements": "Stable income, positive credit profile, affordability checks.",
        "benefits": "Stronger value for regular spenders wanting a bank-wide rewards programme.",
        "risks": "Reward value depends on active participation and disciplined payment behaviour.",
        "pros": "Better rewards potential\nGood travel usability\nCompetitive mainstream tier",
        "cons": "Monthly fee higher than entry cards\nPremium lounge perks not included",
        "categories": "Rewards,Travel,Everyday",
        "tier": "Gold",
        "is_featured": True,
        "brochure_link": "https://www.absa.co.za/personal/credit-cards/",
    },
    {
        "name": "Nedbank Gold Credit Card",
        "banks": "Nedbank",
        "card_type": "Credit",
        "interest_rate": "From prime + 5%",
        "interest_free_days": 55,
        "monthly_fee": 55.0,
        "annual_fee": 0.0,
        "min_income": "R5,000+ / month",
        "limit_range": "R5,000 to R110,000",
        "reward_type": "Greenbacks",
        "rewards_summary": "Mainstream rewards card suited to everyday spend, online shopping, and controlled credit-building.",
        "travel_features": "Travel booking access via Nedbank channels.",
        "lifestyle_features": "Greenbacks earn on qualifying spend and digital banking controls.",
        "insurance": "Card fraud protection and optional cover",
        "discounts": "Partner shopping and fuel promotions",
        "requirements": "Nedbank affordability review, income proof, SA residency.",
        "benefits": "Solid all-rounder for users who want rewards without ultra-premium pricing.",
        "risks": "Greenbacks value depends on card usage and linked product mix.",
        "pros": "Popular rewards ecosystem\nFlexible limits\nGood app experience",
        "cons": "Premium travel perks reserved for upper tiers\nInterest still punitive on carried balances",
        "categories": "Rewards,Everyday",
        "tier": "Gold",
        "is_featured": True,
        "brochure_link": "https://personal.nedbank.co.za/cards/credit-cards.html",
    },
    {
        "name": "Nedbank Platinum Credit Card",
        "banks": "Nedbank",
        "card_type": "Credit",
        "interest_rate": "From prime + 3.5%",
        "interest_free_days": 55,
        "monthly_fee": 80.0,
        "annual_fee": 0.0,
        "min_income": "R25,000+ / month",
        "limit_range": "R40,000 to R250,000",
        "reward_type": "Greenbacks",
        "rewards_summary": "Premium travel and lifestyle card with elevated Greenbacks earn and premium servicing.",
        "travel_features": "Airport lounge access, travel booking support, premium Visa benefits.",
        "lifestyle_features": "Enhanced rewards earn, concierge access, premium service desk.",
        "insurance": "Travel insurance and purchase protection on qualifying spend",
        "discounts": "Premium partner offers across travel and lifestyle",
        "requirements": "Higher income threshold, stronger credit history, bank affordability review.",
        "benefits": "Appeals to frequent travellers and higher-income professionals.",
        "risks": "Best value comes from consistent spend and frequent use of included perks.",
        "pros": "Premium travel value\nHigher rewards earn\nStrong service proposition",
        "cons": "Higher monthly cost\nNot ideal for low utilisation customers",
        "categories": "Travel,Rewards,Lifestyle",
        "tier": "Platinum",
        "brochure_link": "https://personal.nedbank.co.za/cards/credit-cards.html",
    },
    {
        "name": "FNB Aspire Credit Card",
        "banks": "FNB",
        "card_type": "Credit",
        "interest_rate": "Personalised",
        "interest_free_days": 55,
        "monthly_fee": 45.0,
        "annual_fee": 0.0,
        "min_income": "R84,000+ / year",
        "limit_range": "R6,000 to R100,000",
        "reward_type": "eBucks",
        "rewards_summary": "Aspire gives younger professionals an accessible path into the eBucks ecosystem and digital banking stack.",
        "travel_features": "Travel discounts through eBucks travel partners.",
        "lifestyle_features": "App-first banking, nav-driven spend controls, everyday rewards.",
        "insurance": "Optional card and debt protection",
        "discounts": "Fuel, grocery, and partner offers through eBucks",
        "requirements": "Income qualification and affordability checks within the FNB profile.",
        "benefits": "Good bridge between starter credit and richer rewards banking.",
        "risks": "eBucks outcomes depend on behaviour, account structure, and compliance with programme rules.",
        "pros": "Popular rewards programme\nYouth-friendly positioning\nStrong app tools",
        "cons": "Value tied to broader FNB ecosystem\nTravel perks are lighter than Premier or Private tiers",
        "categories": "Rewards,Everyday,Lifestyle",
        "tier": "Standard",
        "brochure_link": "https://www.fnb.co.za/credit-cards/",
    },
    {
        "name": "FNB Premier Credit Card",
        "banks": "FNB",
        "card_type": "Credit",
        "interest_rate": "Personalised",
        "interest_free_days": 55,
        "monthly_fee": 88.0,
        "annual_fee": 0.0,
        "min_income": "R300,000+ / year",
        "limit_range": "R25,000 to R250,000",
        "reward_type": "eBucks",
        "rewards_summary": "Premium lifestyle and travel-focused card with elevated eBucks and higher service levels.",
        "travel_features": "Airport lounge access, travel booking perks, and international acceptance.",
        "lifestyle_features": "Concierge-style support, dining offers, premium digital controls.",
        "insurance": "Travel cover and card protection on qualifying transactions",
        "discounts": "Higher-tier eBucks partner savings",
        "requirements": "Premier income segment and FNB affordability profile.",
        "benefits": "Strong option for digitally engaged earners who travel regularly.",
        "risks": "Premium pricing needs active engagement to justify the total value.",
        "pros": "Excellent ecosystem rewards\nTravel friendly\nStrong digital experience",
        "cons": "Requires higher income\nSome value locked behind overall banking behaviour",
        "categories": "Travel,Rewards,Lifestyle",
        "tier": "Platinum",
        "is_featured": True,
        "brochure_link": "https://www.fnb.co.za/credit-cards/",
    },
    {
        "name": "Discovery Gold Credit Card",
        "banks": "Discovery",
        "card_type": "Credit",
        "interest_rate": "Personalised",
        "interest_free_days": 55,
        "monthly_fee": 65.0,
        "annual_fee": 0.0,
        "min_income": "R10,000+ / month",
        "limit_range": "R10,000 to R150,000",
        "reward_type": "Discovery Miles",
        "rewards_summary": "Healthy-living linked card that suits Discovery ecosystem members who want Miles back on qualifying spend.",
        "travel_features": "Miles can support flights and travel redemptions.",
        "lifestyle_features": "Boosted rewards for engaged Vitality customers and app-first card management.",
        "insurance": "Card fraud protection and optional cover",
        "discounts": "Discovery Miles partner discounts across health, retail, and travel",
        "requirements": "Affordability and standard credit checks; higher value if paired with Discovery products.",
        "benefits": "Compelling for customers already invested in the Discovery stack.",
        "risks": "Rewards are strongest when multiple Discovery behaviours are maintained.",
        "pros": "Strong ecosystem rewards\nWellness-linked value\nModern digital servicing",
        "cons": "Less compelling outside Discovery ecosystem\nPremium value depends on engagement",
        "categories": "Rewards,Lifestyle,Travel",
        "tier": "Gold",
        "brochure_link": "https://www.discovery.co.za/bank/credit-cards",
    },
    {
        "name": "Discovery Platinum Credit Card",
        "banks": "Discovery",
        "card_type": "Credit",
        "interest_rate": "Personalised",
        "interest_free_days": 55,
        "monthly_fee": 105.0,
        "annual_fee": 0.0,
        "min_income": "R35,000+ / month",
        "limit_range": "R40,000 to R300,000",
        "reward_type": "Discovery Miles",
        "rewards_summary": "Higher-tier Discovery card with stronger Miles earning, more lifestyle access, and travel-ready value.",
        "travel_features": "Travel privileges, premium servicing, and airport-linked benefits on qualifying packages.",
        "lifestyle_features": "Enhanced rewards acceleration and premium service interactions.",
        "insurance": "Enhanced travel and purchase protection on qualifying spend",
        "discounts": "Premium partner discounts across Discovery-linked merchants",
        "requirements": "Stronger income and affordability profile with premium underwriting.",
        "benefits": "Designed for higher-income users who want a lifestyle-driven rewards card.",
        "risks": "High value depends on frequent use of Miles and premium ecosystem benefits.",
        "pros": "Higher reward ceiling\nTravel-ready\nPremium support",
        "cons": "Higher monthly fee\nBest fit for existing Discovery customers",
        "categories": "Travel,Rewards,Lifestyle",
        "tier": "Platinum",
        "brochure_link": "https://www.discovery.co.za/bank/credit-cards",
    },
    {
        "name": "Woolworths Gold Credit Card",
        "banks": "Woolworths",
        "card_type": "Credit",
        "interest_rate": "Personalised",
        "interest_free_days": 55,
        "monthly_fee": 39.0,
        "annual_fee": 0.0,
        "min_income": "R5,000+ / month",
        "limit_range": "R4,000 to R120,000",
        "reward_type": "WRewards",
        "rewards_summary": "Retail-centric card tailored to shoppers who want value back inside the Woolworths ecosystem.",
        "travel_features": "Limited travel positioning; focused on domestic retail spend value.",
        "lifestyle_features": "WRewards-linked offers and digital card servicing.",
        "insurance": "Standard fraud protection",
        "discounts": "Woolworths-linked discounts and campaign offers",
        "requirements": "Income proof, affordability assessment, and qualifying credit profile.",
        "benefits": "Strong fit for loyal Woolworths spenders looking for straightforward card benefits.",
        "risks": "Rewards skew heavily toward Woolworths ecosystem value rather than broad travel or cash rewards.",
        "pros": "Retail value for loyal shoppers\nAccessible pricing\nSimple proposition",
        "cons": "Narrower rewards utility\nFewer premium perks",
        "categories": "Everyday,Lifestyle,Rewards",
        "tier": "Gold",
        "brochure_link": "https://www.woolworths.co.za/content/financial-services/credit-card",
    },
    {
        "name": "Woolworths Black Credit Card",
        "banks": "Woolworths",
        "card_type": "Credit",
        "interest_rate": "Personalised",
        "interest_free_days": 55,
        "monthly_fee": 89.0,
        "annual_fee": 0.0,
        "min_income": "R35,000+ / month",
        "limit_range": "R40,000 to R250,000",
        "reward_type": "WRewards",
        "rewards_summary": "Premium Woolworths card with elevated retail rewards, travel utility, and stronger lifestyle positioning.",
        "travel_features": "Premium assistance and international card acceptance.",
        "lifestyle_features": "Elevated retailer rewards, concierge-style touches, premium store-linked offers.",
        "insurance": "Travel and purchase protection on qualifying purchases",
        "discounts": "Higher-tier Woolworths and partner offers",
        "requirements": "Higher income threshold and stronger affordability profile.",
        "benefits": "Best for loyal premium Woolworths shoppers who still want a general-use Visa credit card.",
        "risks": "Value is less compelling if Woolworths spend is limited.",
        "pros": "Premium retail rewards\nGood lifestyle fit\nBetter limits",
        "cons": "Higher fee\nBest value tied to one retail ecosystem",
        "categories": "Lifestyle,Rewards,Everyday",
        "tier": "Platinum",
        "brochure_link": "https://www.woolworths.co.za/content/financial-services/credit-card",
    },
    {
        "name": "Standard Bank Blue Credit Card",
        "banks": "Standard Bank",
        "card_type": "Credit",
        "interest_rate": "Personalised",
        "interest_free_days": 55,
        "monthly_fee": 40.0,
        "annual_fee": 0.0,
        "min_income": "R5,000+ / month",
        "limit_range": "R5,000 to R80,000",
        "reward_type": "UCount",
        "rewards_summary": "Entry-level Standard Bank option with app controls and a path into the UCount ecosystem.",
        "travel_features": "Global card acceptance and travel-ready online control.",
        "lifestyle_features": "Mobile-first controls, spend tracking, and UCount participation.",
        "insurance": "Basic card protection",
        "discounts": "UCount partner discounts and merchant campaigns",
        "requirements": "Standard affordability and credit profile review.",
        "benefits": "Useful for everyday spenders wanting mainstream bank rewards and simple credit access.",
        "risks": "Entry-tier rewards are modest without broader UCount participation.",
        "pros": "Trusted issuer\nUseful app experience\nManageable fee level",
        "cons": "Limited premium perks\nRewards strengthen only with broader ecosystem engagement",
        "categories": "Everyday,Rewards",
        "tier": "Standard",
        "brochure_link": "https://www.standardbank.co.za/southafrica/personal/products-and-services/bank-with-us/borrow-for-your-needs/credit-cards",
    },
    {
        "name": "Standard Bank Platinum Credit Card",
        "banks": "Standard Bank",
        "card_type": "Credit",
        "interest_rate": "Personalised",
        "interest_free_days": 55,
        "monthly_fee": 96.0,
        "annual_fee": 0.0,
        "min_income": "R25,000+ / month",
        "limit_range": "R40,000 to R250,000",
        "reward_type": "UCount",
        "rewards_summary": "Premium UCount card built for higher-income earners wanting travel and lifestyle flexibility.",
        "travel_features": "Airport lounges, travel conveniences, and international benefits on qualifying packages.",
        "lifestyle_features": "Enhanced UCount earning, premium servicing, and broader protection benefits.",
        "insurance": "Travel inconvenience and purchase protection on qualifying spend",
        "discounts": "Premium merchant and travel-linked offers",
        "requirements": "Premium affordability threshold and stronger credit history.",
        "benefits": "Appeals to established professionals who want a premium bank proposition.",
        "risks": "Premium monthly cost requires active use of travel or rewards benefits.",
        "pros": "Premium bank benefits\nGood travel proposition\nBroader protection",
        "cons": "Higher fee\nValue depends on active UCount engagement",
        "categories": "Travel,Rewards,Lifestyle",
        "tier": "Platinum",
        "brochure_link": "https://www.standardbank.co.za/southafrica/personal/products-and-services/bank-with-us/borrow-for-your-needs/credit-cards",
    },
    {
        "name": "Diners Club Silver Credit Card",
        "banks": "Diners",
        "card_type": "Charge",
        "interest_rate": "Balance due monthly",
        "interest_free_days": 30,
        "monthly_fee": 60.0,
        "annual_fee": 720.0,
        "min_income": "R18,000+ / month",
        "limit_range": "Subject to profile and spend behaviour",
        "reward_type": "ClubMiles",
        "rewards_summary": "Travel-oriented charge card with lounge access and classic Diners Club positioning.",
        "travel_features": "Airport lounge access, travel-linked privileges, global Diners acceptance where supported.",
        "lifestyle_features": "Dining and travel lifestyle benefits with premium feel.",
        "insurance": "Travel insurance on qualifying journeys",
        "discounts": "Travel and hospitality partner offers",
        "requirements": "Good credit standing, premium income profile, and monthly settlement ability.",
        "benefits": "Strong for cardholders who value lounge and travel status benefits.",
        "risks": "Charge-card discipline required because balances are expected to settle regularly.",
        "pros": "Travel positioning\nLounge benefits\nDistinct premium brand",
        "cons": "Acceptance not as broad as Visa/Mastercard\nAnnual cost is meaningful",
        "categories": "Travel,Lifestyle",
        "tier": "Gold",
        "brochure_link": "https://www.dinersclub.co.za/",
    },
    {
        "name": "Diners Club International Credit Card",
        "banks": "Diners",
        "card_type": "Charge",
        "interest_rate": "Balance due monthly",
        "interest_free_days": 30,
        "monthly_fee": 95.0,
        "annual_fee": 1140.0,
        "min_income": "R30,000+ / month",
        "limit_range": "Profile based",
        "reward_type": "ClubMiles",
        "rewards_summary": "Higher-tier Diners option for travellers who want premium service, access, and classic charge-card status.",
        "travel_features": "Expanded lounge and international lifestyle access.",
        "lifestyle_features": "Premium hospitality, concierge, and travel-linked service layers.",
        "insurance": "Travel cover and premium assistance benefits",
        "discounts": "Selected hospitality and travel partnerships",
        "requirements": "Premium underwriting and proven repayment ability.",
        "benefits": "Targets frequent travellers and status-conscious spenders.",
        "risks": "Works best when the full premium travel stack is used regularly.",
        "pros": "Premium status product\nTravel access\nClubMiles rewards",
        "cons": "Higher annual cost\nMore limited acceptance footprint",
        "categories": "Travel,Lifestyle,Rewards",
        "tier": "Platinum",
        "brochure_link": "https://www.dinersclub.co.za/",
    },
    {
        "name": "Investec Visa Platinum Credit Card",
        "banks": "Investec",
        "card_type": "Credit",
        "interest_rate": "Personalised",
        "interest_free_days": 45,
        "monthly_fee": 145.0,
        "annual_fee": 0.0,
        "min_income": "Private banking profile",
        "limit_range": "Profile based premium limits",
        "reward_type": "Investec Rewards",
        "rewards_summary": "Premium private banking-linked card focused on service, global usability, and affluent lifestyle value.",
        "travel_features": "Travel assistance, airport-linked benefits, and premium international acceptance.",
        "lifestyle_features": "Dedicated banker support, premium digital servicing, and curated partner value.",
        "insurance": "Travel and purchase protections subject to programme rules",
        "discounts": "Premium merchant and travel offers",
        "requirements": "Private banking relationship and strong affordability profile.",
        "benefits": "Best suited to affluent professionals who value service quality and flexibility.",
        "risks": "Not optimised for entry-level borrowers or users chasing low-cost credit only.",
        "pros": "Premium service proposition\nGood global utility\nStrong brand cachet",
        "cons": "Higher access threshold\nLimited fit for mainstream shoppers",
        "categories": "Travel,Lifestyle,Rewards",
        "tier": "Platinum",
        "is_featured": True,
        "brochure_link": "https://www.investec.com/en_za/banking/private-bank-account/cards.html",
    },
    {
        "name": "Investec Visa Signature Credit Card",
        "banks": "Investec",
        "card_type": "Credit",
        "interest_rate": "Personalised",
        "interest_free_days": 45,
        "monthly_fee": 185.0,
        "annual_fee": 0.0,
        "min_income": "Private banking / HNW profile",
        "limit_range": "High-value premium limits",
        "reward_type": "Investec Rewards",
        "rewards_summary": "Top-end Investec card for globally mobile clients who want premium service and elevated card prestige.",
        "travel_features": "Premium travel support, elite benefits, and higher-end card services.",
        "lifestyle_features": "Concierge, premium hospitality, curated client experiences.",
        "insurance": "Comprehensive travel-linked protections on qualifying spend",
        "discounts": "Premium partner lifestyle and travel offers",
        "requirements": "Affluent profile and private banking qualification.",
        "benefits": "Works for high-achievers seeking premium flexibility and brand-level service.",
        "risks": "Premium-fee logic depends on active travel and high-value usage.",
        "pros": "Elite service\nPrestige positioning\nGlobal usability",
        "cons": "Niche audience\nPremium cost structure",
        "categories": "Travel,Lifestyle,Rewards",
        "tier": "Signature",
        "brochure_link": "https://www.investec.com/en_za/banking/private-bank-account/cards.html",
    },
    {
        "name": "RMB Private Bank World Debit Credit Card",
        "banks": "RMB",
        "card_type": "Credit",
        "interest_rate": "Personalised",
        "interest_free_days": 55,
        "monthly_fee": 160.0,
        "annual_fee": 0.0,
        "min_income": "Private bank segment",
        "limit_range": "Premium profile-based limits",
        "reward_type": "eBucks",
        "rewards_summary": "Private bank card that blends premium service, travel convenience, and an executive rewards stack.",
        "travel_features": "Lounge access, global usability, premium travel servicing.",
        "lifestyle_features": "Private bank support, high-touch servicing, premium app controls.",
        "insurance": "Travel and purchase protection on qualifying transactions",
        "discounts": "Executive-level travel and lifestyle offers",
        "requirements": "RMB private bank eligibility, strong income, and affordability assessment.",
        "benefits": "Good fit for entrepreneurs and executives who travel and bank deeply inside the RMB/FNB ecosystem.",
        "risks": "Premium value depends on active use of the private bank service suite.",
        "pros": "Executive service\nTravel benefits\nPrivate bank positioning",
        "cons": "Limited accessibility\nValue relies on broader ecosystem participation",
        "categories": "Business,Travel,Rewards",
        "tier": "Signature",
        "brochure_link": "https://www.rmbprivatebank.com/",
    },
    {
        "name": "RMB Fusion Credit Facility",
        "banks": "RMB",
        "card_type": "Fusion",
        "interest_rate": "Personalised",
        "interest_free_days": 55,
        "monthly_fee": 180.0,
        "annual_fee": 0.0,
        "min_income": "Private bank segment",
        "limit_range": "Premium profile-based limits",
        "reward_type": "eBucks",
        "rewards_summary": "Integrated transactional and credit facility for entrepreneurs and professionals who want one premium banking interface.",
        "travel_features": "Travel support and global digital wallet compatibility.",
        "lifestyle_features": "Consolidated cash-flow management with executive service support.",
        "insurance": "Travel-linked protections depending on programme terms",
        "discounts": "Selected private bank and eBucks-linked offers",
        "requirements": "RMB private bank qualification and advanced affordability review.",
        "benefits": "Useful for clients wanting a premium all-in-one spend and liquidity product.",
        "risks": "Integrated facilities require disciplined oversight to avoid overextension.",
        "pros": "Integrated product design\nExecutive service\nDigital convenience",
        "cons": "Not for entry-level users\nPremium pricing and qualification",
        "categories": "Business,Everyday,Rewards",
        "tier": "Signature",
        "brochure_link": "https://www.rmbprivatebank.com/",
    },
]


def seed_cards():
    created = 0
    updated = 0
    for payload in SEED_CARDS:
        card = CreditCard.query.filter_by(name=payload["name"]).first()
        is_new = card is None
        if is_new:
            card = CreditCard(name=payload["name"], card_type=payload["card_type"], banks=payload["banks"])
            db.session.add(card)

        for key, value in payload.items():
            setattr(card, key, value)

        if is_new:
            created += 1
        else:
            updated += 1

    db.session.commit()
    print(f"Seed complete: {created} created, {updated} updated, total payloads {len(SEED_CARDS)}")


if __name__ == "__main__":
    with application.app_context():
        seed_cards()
